INSERT OR IGNORE INTO "bricktracker_individual_minifigure_parts" (
    "id",
    "part",
    "color",
    "spare",
    "quantity",
    "element",
    "rebrickable_inventory",
    "counterpart",
    "alternate",
    "match_id",
    "missing",
    "damaged",
    "checked"
) VALUES (
    :id,
    :part,
    :color,
    :spare,
    :quantity,
    :element,
    :rebrickable_inventory,
    :counterpart,
    :alternate,
    :match_id,
    0,
    0,
    0
)
